package jcf;

/**
 * Auto-generated by JettraEE from jettra-config.properties.
 */
public enum AppRole {
    ADMIN,
    MANAGER,
    USER,
    SXRM;

    public String getValue() {
        return name();
    }
}
