package jcf;

/**
 * Auto-generated by JettraAppServer from jettra-config.properties.
 */
public class systemRole {
    public static final String ADMIN = "ADMIN";
    public static final String MANAGER = "MANAGER";
    public static final String DEMO = "DEMO";
}
